"use strict";

module.exports = {
    INITIALIZE: 'INITIALIZE',
    CREATE_LIST: 'CREATE_LIST',
    UPDATE_LIST: 'UPDATE_LIST',
    DELETE_LIST: 'DELETE_LIST',
    CREATE_TASK: 'CREATE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK'
};
